### PR TITLE
Change commit hash for ogre-2.1-release

### PR DESCRIPTION
**Pull request by Crola1702**
Signed-off-by: Crola1702 <cristobal.arroyo@ekumenlabs.com>

### CODE REVIEW

**Comment by j-rivero** [comment]
we need to update the hash sha512

**Comment by Crola1702** [comment]
> we need to update the hash sha512
How do I get the SHA512?

**Comment by j-rivero** [comment]
If I remember correctly, the vcpkg function is taking the code from github which allows you to download a zip directly from the commit page that github shows you. You can download it and run sha512sum command.

**Comment by Crola1702** [comment]
@j-rivero How can we test that this is the right change?

**Review by j-rivero — APPROVED** [review]
great!

**Pull request merged**
